---
- name: This Playbook to set-up Kubernetes using k3s
  hosts: kubcluster
  become: true
  tasks:

  - name: To update the packages
    command: sudo apt-get update

  - name: To install docker
    command: sudo apt install docker.io -y

  - name: To start docker service
    command: sudo systemctl start docker

  
  
